### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Rudloff** [KevinParker10/CodeMineProject1#5]
Hello,

I'm testing your app on Android 6.0.1.
It crashes when I touch a part:
```
05-14 22:00:51.691 32222 32222 E AndroidRuntime: Process: com.codemine.unofficial.pcpartpicker, PID: 32222
05-14 22:00:51.691 32222 32222 E AndroidRuntime: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:672)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:659)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at com.codemine.unofficial.pcpartpicker.ComputerPartAdapter$1.onClick(ComputerPartAdapter.java:64)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.view.View.performClick(View.java:5205)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21164)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-14 22:00:51.691 32222 32222 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-14 22:00:51.695  2125  4163 W ActivityManager:   Force finishing activity com.codemine.unofficial.pcpartpicker/.PowerActivity
```

**Comment by asdiamond** [comment]
can you upload some images, along with a description and the callstack of the exception please? I will try and fix it as soon as possible if you can do that.

**Comment by Rudloff** [comment]
Here is a screenshot:
![screenshot_20180516-120724](https://user-images.githubusercontent.com/840125/40111016-d8aac342-5901-11e8-8e0b-3d04a3c2efe3.png)
This happens when I touch any part (then the app closes).

I posted the logcat callstack in my previous post. Do you need something else?
